# Generated by Django 4.1.4 on 2023-01-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
