# Generated by Django 4.1.4 on 2023-01-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_customer_financeofficer_manager_poitems_pritems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='financeofficer',
            name='finance_officer_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='salesman_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='salesman_password',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
