# Generated by Django 4.1.4 on 2023-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_customer_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='PurchaseRequisitions',
            name='customer_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
