# Generated by Django 4.1.4 on 2023-01-08 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_remove_customer_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeofficer',
            name='finance_officer_email',
        ),
        migrations.RemoveField(
            model_name='financeofficer',
            name='finance_officer_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='financeofficer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financeofficer',
            name='finance_officer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
