# Generated by Django 4.1.4 on 2023-01-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_financeofficer_finance_officer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='salesman_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
