# Generated by Django 4.1.4 on 2023-01-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeofficer',
            name='finance_officer_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
