# Generated by Django 4.1.4 on 2023-01-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_financeofficer_finance_officer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pritems',
            name='pr_item_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotationitems',
            name='q_item_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
