# Generated by Django 4.1.4 on 2023-01-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_pritems_pr_item_id_alter_purchaseorder_po_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pritems',
            name='pr_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotationitems',
            name='q_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
