# Generated by Django 4.1.4 on 2023-01-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_pritems_pr_item_id_alter_purchaseorder_po_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitems',
            name='po_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
