# Generated by Django 4.1.4 on 2023-01-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_purchaseorder_number_of_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='number_of_items',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
