# Generated by Django 4.1.5 on 2023-01-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_quotation_number_of_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='manager_id',
            field=models.ForeignKey(default='MAN0001', on_delete=django.db.models.deletion.CASCADE, to='project.manager'),
        ),
    ]
