# Generated by Django 4.1.4 on 2023-01-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_quotation_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pritems',
            name='pr_item_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
