# Generated by Django 4.1.4 on 2023-01-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_pritems_pr_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pritems',
            name='pr_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
