# Generated by Django 4.1.5 on 2023-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='number_of_items',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
