# Generated by Django 4.1.4 on 2023-01-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_pritems_pr_item_id'),
        ('project', '0019_purchaserequisition_number_of_items'),
    ]

    operations = [
    ]
